#define moveL 'L'
#define moveR 'R'
#define moveF 'F'
#define moveB 'B'
#define actuatorBackU '8'
#define actuatorBackD '2'
#define actuatorFrontU '7'
#define actuatorFrontD '1'
#define armBaseL '4'
#define armBaseR '6'
#define wristRotateL 'T'
#define wristRotateR 'K'
#define wristClose  'C'
#define wristOpen  'D'
#define bodyCamU 'U'
#define bodyCamD 'H'
#define bodyCamL 'W'
#define bodyCamR 'Q'
#define actuatorCamR 'X'
#define actuatorCamL 'Y'
#define SciTaskBaseL 'P'
#define SciTaskBaseR 'O'
#define SensorServoU 'J'
#define SensorServoD 'N'

#define STOP 'S'


